### ISSUE TITLE
Error while running code

### ISSUE THREAD

**Issue by genesis231** [sgitkene/yowbot#1]
yowbot-master# python3 run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from layer2 import RelayLayer
  File "/home/starkcenter/Desktop/project_tasta/tg/yowbot-master/layer2.py", line 1, in <module>
    from yowsup.layers.interface                          import YowInterfaceLayer, ProtocolEntityCallback
  File "/home/starkcenter/Desktop/project_tasta/tg/yowbot-master/yowsup/layers/interface/**init**.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/home/starkcenter/Desktop/project_tasta/tg/yowbot-master/yowsup/layers/interface/interface.py", line 2, in <module>
    from yowsup.layers.protocol_iq.protocolentities import IqProtocolEntity
  File "/home/starkcenter/Desktop/project_tasta/tg/yowbot-master/yowsup/layers/protocol_iq/**init**.py", line 1, in <module>
    from .layer import YowIqProtocolLayer
  File "/home/starkcenter/Desktop/project_tasta/tg/yowbot-master/yowsup/layers/protocol_iq/layer.py", line 7, in <module>
    from yowsup.layers.auth import YowAuthenticationProtocolLayer
  File "/home/starkcenter/Desktop/project_tasta/tg/yowbot-master/yowsup/layers/auth/**init**.py", line 2, in <module>
    from .layer_authentication import YowAuthenticationProtocolLayer
  File "/home/starkcenter/Desktop/project_tasta/tg/yowbot-master/yowsup/layers/auth/layer_authentication.py", line 3, in <module>
    from yowsup.common.tools import TimeTools
  File "/home/starkcenter/Desktop/project_tasta/tg/yowbot-master/yowsup/common/tools.py", line 2, in <module>
    from dateutil import tz
ImportError: No module named 'dateutil'

**Comment by sgitkene** [comment]
thanks, I guess my dependencies are incomplete. if you download respective dependencies for yowsup tg and pytg the issue should resolve itself. I will adjust dependencies in the readme.md

**Comment by sgitkene** [comment]
I assume you downloaded the dependencies and it worked. I also corrected the readme.
